"""
Tests parmed.formats package
"""
from __future__ import division
import utils

import numpy as np
from parmed import amber, charmm, exceptions, formats, gromacs, residue
from parmed import (Structure, read_PDB, write_PDB, read_CIF, write_CIF,
                    download_PDB, download_CIF)
from parmed.modeller import ResidueTemplate, ResidueTemplateContainer
from parmed.utils.six import iteritems
from parmed.utils.six.moves import zip, StringIO
import random
import os
import unittest
from utils import (get_fn, has_numpy, diff_files, get_saved_fn, skip_big_tests,
                   FileIOTestCase)

def reset_stringio(io):
    """ Resets a StringIO instance to "empty-file" state """
    io.seek(0)
    io.truncate()
    return io

class TestFileLoader(FileIOTestCase):
    """ Tests the automatic file loader """

    def testLoadOFF(self):
        """ Tests automatic loading of OFF files """
        off = formats.load_file(get_fn('amino12.lib'))
        self.assertIsInstance(off, dict)
        for key, item in iteritems(off):
            self.assertIsInstance(item, ResidueTemplate)

    def testLoadAmberParm(self):
        """ Tests automatic loading of AmberParm object """
        parm = formats.load_file(get_fn('trx.prmtop'))
        self.assertIsInstance(parm, amber.AmberParm)

    def testLoadAmoebaParm(self):
        """ Tests automatic loading of AmoebaParm object """
        parm = formats.load_file(get_fn('amoeba.parm7'))
        self.assertIsInstance(parm, amber.AmoebaParm)

    def testLoadChamberParm(self):
        """ Tests automatic loading of ChamberParm object """
        parm = formats.load_file(get_fn('ala_ala_ala.parm7'))
        self.assertIsInstance(parm, amber.ChamberParm)

    def testLoadAmberFormat(self):
        """ Tests automatic loading of RISM mdl (AmberFormat) object """
        parm = formats.load_file(get_fn('cSPCE.mdl'))
        self.assertIsInstance(parm, amber.AmberFormat)
        self.assertNotIsInstance(parm, amber.AmberParm)

    def testLoadAmberRestart(self):
        """ Tests automatic loading of Amber ASCII restart file """
        parm = formats.load_file(get_fn('trx.inpcrd'))
        self.assertIsInstance(parm, amber.AmberAsciiRestart)

    def testLoadAmberMdcrd(self):
        """ Tests automatic loading of Amber mdcrd file """
        crd = formats.load_file(get_fn('tz2.truncoct.crd'), natom=5827,
                                hasbox=True)
        self.assertIsInstance(crd, amber.AmberMdcrd)
        self.assertRaises(TypeError, lambda:
                formats.load_file(get_fn('tz2.truncoct.crd')))

    def testLoadCharmmPsfFile(self):
        """ Tests automatic loading of CHARMM PSF file """
        parm = formats.load_file(get_fn('ala_ala_ala.psf'))
        self.assertIsInstance(parm, charmm.CharmmPsfFile)

    def testLoadCharmmCrdFile(self):
        """ Tests automatic loading of CHARMM crd file """
        crd = formats.load_file(get_fn('dhfr_min_charmm.crd'))
        self.assertIsInstance(crd, charmm.CharmmCrdFile)

    def testLoadCharmmRestart(self):
        """ Tests automatic loading of CHARMM restart file """
        crd = formats.load_file(get_fn('sample-charmm.rst'))
        self.assertIsInstance(crd, charmm.CharmmRstFile)

    def testLoadNetCDFRestart(self):
        """ Tests automatic loading of Amber NetCDF restart file """
        if amber.HAS_NETCDF:
            crd = formats.load_file(get_fn('ncinpcrd.rst7'))
            self.assertIsInstance(crd, amber.NetCDFRestart)
        else:
            self.assertRaises(exceptions.FormatNotFound, lambda:
                    formats.load_file(get_fn('ncinpcrd.rst7')))

    def testLoadNetCDFTraj(self):
        """ Tests automatic loading of Amber NetCDF trajectory file """
        if amber.HAS_NETCDF:
            crd = formats.load_file(get_fn('tz2.truncoct.nc'))
            self.assertIsInstance(crd, amber.NetCDFTraj)
        else:
            self.assertRaises(exceptions.FormatNotFound, lambda:
                    formats.load_file(get_fn('ncinpcrd.rst7')))

    def testLoadPDB(self):
        """ Tests automatic loading of PDB files """
        pdb = formats.load_file(get_fn('4lzt.pdb'))
        self.assertIsInstance(pdb, Structure)
        self.assertEqual(len(pdb.atoms), 1164)

    def testLoadReducePDB(self):
        """ Tests automatic loading of PDB files generated by reduce """
        self.assertTrue(formats.PDBFile.id_format(get_fn('reduce.pdb')))
        pdb = formats.load_file(get_fn('reduce.pdb'))
        self.assertIsInstance(pdb, Structure)
        self.assertEqual(len(pdb.atoms), 49)
        self.assertEqual(len(pdb.residues), 1)
        self.assertEqual(pdb.residues[0].name, 'SAM')

    def testLoadCIF(self):
        """ Tests automatic loading of PDBx/mmCIF files """
        cif = formats.load_file(get_fn('4LZT.cif'))
        self.assertIsInstance(cif, Structure)
        self.assertEqual(len(cif.atoms), 1164)

    def testLoadMol2(self):
        """ Tests automatic loading of mol2 and mol3 files """
        mol2 = formats.load_file(get_fn('test_multi.mol2'))
        self.assertIsInstance(mol2, ResidueTemplateContainer)
        mol3 = formats.load_file(get_fn('tripos9.mol2'))
        self.assertIsInstance(mol3, ResidueTemplate)

    def testLoadGromacsTop(self):
        """ Tests automatic loading of Gromacs topology file """
        top = formats.load_file(get_fn('1aki.charmm27.top'))
        self.assertIsInstance(top, gromacs.GromacsTopologyFile)

    def testLoadGromacsGro(self):
        """ Tests automatic loading of Gromacs GRO file """
        gro = formats.load_file(get_fn('1aki.ff99sbildn.gro'))
        self.assertIsInstance(gro, Structure)

    def testLoadPQR(self):
        """ Tests automatic loading of PQR files """
        pqr = formats.load_file(get_fn('adk_open.pqr'))
        self.assertIsInstance(pqr, Structure)
        self.assertEqual(len(pqr.atoms), 3341)
        self.assertEqual(len(pqr.residues), 214)
        self.assertAlmostEqual(sum(a.charge for a in pqr.atoms), -4, places=4)
        self.assertEqual(pqr.atoms[0].charge, -0.30)
        self.assertEqual(pqr.atoms[0].radii, 1.85)
        self.assertEqual(pqr.atoms[0].atomic_number, 7)
        self.assertEqual(pqr.atoms[35].charge, -0.8)
        self.assertEqual(pqr.atoms[-1].charge, -0.67)
        self.assertEqual(pqr.atoms[-1].radii, 1.7)
        self.assertEqual(pqr.atoms[-1].atomic_number, 8)
        self.assertIsInstance(random.choice(pqr.residues).number, int)
        self.assertIsInstance(random.choice(pqr.atoms).number, int)

    def testMisdetectPQR(self):
        """ Check that PQR autodetection does not identify a PDB file """
        pdb = formats.PDBFile.download('3p4a')
        fname = get_fn('3p4a_chainA.pdb', written=True)
        pdb['A',:,:].save(fname)
        self.assertFalse(formats.PQRFile.id_format(fname))

    def testBadLoads(self):
        """ Test exception handling when non-recognized files are loaded """
        self.assertRaises(exceptions.FormatNotFound, lambda:
                formats.load_file(get_fn('../test_parmed_formats.py')))
        self.assertRaises(IOError, lambda: formats.load_file('no_file'))

    def testStructureKeyword(self):
        """ Tests that the structure argument is special-cased in load_file """
        mol2 = formats.load_file(get_fn('tripos9.mol2'), structure=True)
        self.assertIsInstance(mol2, Structure)
        pdb = formats.load_file(get_fn('4lzt.pdb'), structure=True)

    def testNatomHasboxKeyword(self):
        """ Tests that the hasbox/natom arguments are special-cased in load_file """
        crd = formats.load_file(get_fn('tz2.truncoct.crd'), natom=5827,
                                hasbox=True)
        self.assertIsInstance(crd, amber.AmberMdcrd)
        if amber.HAS_NETCDF:
            crd = formats.load_file(get_fn('tz2.truncoct.nc'), natom=5827,
                                    hasbox=True)
            self.assertIsInstance(crd, amber.NetCDFTraj)
        else:
            crd = formats.load_file(get_fn('trx.prmtop'), natom=5827,
                                    hasbox=True)
            self.assertIsInstance(crd, amber.AmberParm)

class TestChemistryPDBStructure(FileIOTestCase):
    
    def setUp(self):
        self.pdb = get_fn('4lzt.pdb')
        self.pdbgz = get_fn('4lzt.pdb.gz')
        self.pdbbz2 = get_fn('4lzt.pdb.bz2')
        self.models = get_fn('2koc.pdb')
        self.overflow = get_fn('4lyt_vmd.pdb')
        self.simple = get_fn('ala_ala_ala.pdb')
        self.format_test = get_fn('SCM_A.pdb')
        self.overflow2 = get_fn('overflow.pdb')
        FileIOTestCase.setUp(self)

    def testAscii(self):
        """ Test PDB file parsing """
        self._check4lzt(read_PDB(self.pdb))
        # The PDB file with multiple models
        pdbfile = read_PDB(open(self.models))
        all_crds = pdbfile.get_coordinates('all')
        self.assertEqual(all_crds.shape[0], 20)
        np.testing.assert_allclose(all_crds[0][0], [-8.886, -5.163, 9.647])
        np.testing.assert_allclose(all_crds[19][-1], [-12.051, 5.205, -2.146])

    def testDownload(self):
        """ Tests downloading PDB files """
        self._check4lzt(download_PDB('4lzt'))

    def testDownloadSave(self):
        """ Tests downloading PDB files and saving a copy """
        fname = get_fn('downloaded.pdb', written=True)
        self._check4lzt(download_PDB('4lzt', saveto=fname))
        self._check4lzt(read_PDB(fname))

    def testPositions(self):
        """ Tests that positions are Vec3's with units """
        from parmed import unit as u
        from parmed import Vec3
        pdbfile = read_PDB(open(self.models))
        self.assertIsInstance(pdbfile.positions[0], u.Quantity)
        self.assertIsInstance(pdbfile.positions[0].value_in_unit(u.angstroms), Vec3)

    def testGzip(self):
        """ Test Gzipped-PDB file parsing """
        self._check4lzt(read_PDB(self.pdbgz))

    def testBzip(self):
        """ Test Bzipped-PDB file parsing """
        self._check4lzt(read_PDB(self.pdbbz2))

    @unittest.skipIf(skip_big_tests(), 'Skipping large tests')
    def testVmdOverflow(self):
        """ Test PDB file where atom and residue numbers overflow """
        pdbfile = read_PDB(self.overflow)
        self.assertEqual(len(pdbfile.atoms), 110237)
        self.assertEqual(len(pdbfile.residues), 35697)
        np.testing.assert_allclose(pdbfile.box, [0, 0, 0, 90, 90, 90])

    @unittest.skipIf(skip_big_tests(), 'Skipping large tests')
    def testRegularOverflow(self):
        """ Test PDB file where atom number goes to ***** after 99999 """
        pdbfile = read_PDB(self.overflow2)
        self.assertEqual(len(pdbfile.atoms), 114277)
        self.assertEqual(len(pdbfile.residues), 25042)
        for i, atom in enumerate(pdbfile.atoms):
            self.assertEqual(atom.number, i+1)
            self.assertEqual(atom.idx, i)

    def testPdbWriteSimple(self):
        """ Test PDB file writing on a very simple input structure """
        pdbfile = read_PDB(self.simple)
        self.assertEqual(len(pdbfile.atoms), 33)
        self.assertEqual(len(pdbfile.residues), 3)
        output = StringIO()
        pdbfile.write_pdb(output)
        output.seek(0)
        pdbfile2 = read_PDB(output)
        self.assertEqual(len(pdbfile2.atoms), 33)
        self.assertEqual(len(pdbfile2.residues), 3)
        self._compareInputOutputPDBs(pdbfile, pdbfile2)

    def testPdbWriteModels(self):
        """ Test PDB file writing from NMR structure with models """
        pdbfile = read_PDB(self.models)
        self.assertEqual(pdbfile.get_coordinates('all').shape, (20, 451, 3))
        self.assertEqual(len(pdbfile.atoms), 451)
        output = StringIO()
        write_PDB(pdbfile, output)
        output.seek(0)
        pdbfile2 = read_PDB(output)
        self.assertEqual(len(pdbfile2.atoms), 451)
        self.assertEqual(pdbfile2.get_coordinates('all').shape, (20, 451, 3))
        np.testing.assert_allclose(pdbfile2.get_coordinates('all'),
                                   pdbfile.get_coordinates('all'))
        self._compareInputOutputPDBs(pdbfile, pdbfile2)

    def testPdbBigCoordinates(self):
        """ Test proper PDB coordinate parsing for large coordinates """
        pdbfile = read_PDB(get_fn('bigz.pdb'))
        self.assertAlmostEqual(pdbfile.coordinates[0,0], -100.024)
        self.assertAlmostEqual(pdbfile.coordinates[0,1], -100.103)
        self.assertAlmostEqual(pdbfile.coordinates[0,2], -100.101)

    def testPdbWriteXtal(self):
        """ Test PDB file writing from a Xtal structure """
        pdbfile = read_PDB(self.pdb)
        self._check4lzt(pdbfile)
        output = StringIO()
        pdbfile.write_pdb(output, renumber=False)
        output.seek(0)
        pdbfile2 = read_PDB(output)
        self._check4lzt(pdbfile2, check_meta=False)
        self._compareInputOutputPDBs(pdbfile, pdbfile2)
        output = reset_stringio(output)
        write_PDB(pdbfile, output)
        output.seek(0)
        pdbfile3 = read_PDB(output)
        self._check4lzt(pdbfile3, check_meta=False)
        self._compareInputOutputPDBs(pdbfile, pdbfile3, True)
        # Now check that renumbering is done correctly. 4lzt skips residues 130
        # through 200
        for res1, res2 in zip(pdbfile.residues, pdbfile3.residues):
            if res1.idx < 129:
                self.assertEqual(res1.number, res2.number)
            elif res1.idx < 135:
                self.assertEqual(res1.number, res2.number + 71)
            else:
                # Some residue numbers are skipped in the water numbering
                self.assertGreaterEqual(res1.number, res2.number + 71 + 794)

    def testPdbWriteAltlocOptions(self):
        """ Test PDB file writing with different altloc options """
        pdbfile = read_PDB(self.pdb)
        self._check4lzt(pdbfile)
        output = StringIO()
        pdbfile.write_pdb(output, renumber=False, altlocs='all')
        output.seek(0)
        pdbfile2 = read_PDB(output)
        self._check4lzt(pdbfile2, check_meta=False)
        self._compareInputOutputPDBs(pdbfile, pdbfile2)
        # Check that 'first' option works
        output = reset_stringio(output)
        pdbfile.write_pdb(output, renumber=False, altlocs='first')
        output.seek(0)
        pdbfile3 = read_PDB(output)
        self._check4lzt(pdbfile3, check_meta=False, has_altloc=False)
        self._compareInputOutputPDBs(pdbfile, pdbfile3, altloc_option='first')
        # Check that the 'occupancy' option works
        output = reset_stringio(output)
        write_PDB(pdbfile, output, renumber=False, altlocs='occupancy')
        output.seek(0)
        pdbfile4 = read_PDB(output)
        self._check4lzt(pdbfile4, check_meta=False, has_altloc=False)
        self._compareInputOutputPDBs(pdbfile, pdbfile4, altloc_option='occupancy')
        # Double-check 'first' vs. 'occupancy'. Residue 85 (SER) has a conformer
        # A that has an occupancy of 0.37 and conformer B with occupancy 0.63
        self.assertEqual(pdbfile3.residues[84][4].xx, -4.162)
        self.assertEqual(pdbfile4.residues[84][4].xx, -4.157)

    def testPdbWriteStandardNames(self):
        """ Test PDB file writing converting to standard names """
        parm = formats.load_file(get_fn('trx.prmtop'), get_fn('trx.inpcrd'))
        output = StringIO()
        write_PDB(parm, output, standard_resnames=True)
        output.seek(0)
        pdb = read_PDB(output)
        for res in pdb.residues:
            self.assertEqual(
                    residue.AminoAcidResidue.get(res.name).abbr, res.name
            )

    def testAnisouRead(self):
        """ Tests that read_PDB properly reads ANISOU records """
        pdbfile = read_PDB(self.pdb)
        aniso1 = [2066, 1204, 1269, 44, 126, 191] # first atom's ANISOU record
        aniso2 = [2090, 1182, 921, 46, 64, 60]    # second atom's ANISOU record
        aniso3 = [3057, 3932, 5304, 126, -937, -661] # last atom's ANISOU
        self.assertEqual(len(aniso1), len(pdbfile.atoms[0].anisou))
        for x, y in zip(aniso1, pdbfile.atoms[0].anisou):
            self.assertEqual(x/10000, y)
        self.assertEqual(len(aniso2), len(pdbfile.atoms[1].anisou))
        for x, y in zip(aniso2, pdbfile.atoms[1].anisou):
            self.assertEqual(x/10000, y)
        self.assertEqual(len(aniso3), len(pdbfile.atoms[-1].anisou))
        for x, y in zip(aniso3, pdbfile.atoms[-1].anisou):
            self.assertEqual(x/10000, y)

    def testAnisouWrite(self):
        """ Tests that write_PDB properly writes ANISOU records """
        def check_aniso(pdbfile):
            aniso1 = [2066, 1204, 1269, 44, 126, 191]
            aniso2 = [2090, 1182, 921, 46, 64, 60]
            aniso3 = [3057, 3932, 5304, 126, -937, -661]
            self.assertEqual(len(aniso1), len(pdbfile.atoms[0].anisou))
            for x, y in zip(aniso1, pdbfile.atoms[0].anisou):
                self.assertEqual(x/10000, y)
            self.assertEqual(len(aniso2), len(pdbfile.atoms[1].anisou))
            for x, y in zip(aniso2, pdbfile.atoms[1].anisou):
                self.assertEqual(x/10000, y)
            self.assertEqual(len(aniso3), len(pdbfile.atoms[-1].anisou))
            for x, y in zip(aniso3, pdbfile.atoms[-1].anisou):
                self.assertEqual(x/10000, y)
        pdbfile = read_PDB(self.pdb)
        check_aniso(pdbfile)
        output = StringIO()
        pdbfile.write_pdb(output)
        output.seek(0)
        pdbfile2 = read_PDB(output)
        # Should have no anisou records, since by default they are not written
        for atom in pdbfile2.atoms:
            self.assertIs(atom.anisou, None)
        output = reset_stringio(output)
        pdbfile.write_pdb(output, renumber=False, write_anisou=True)
        output.seek(0)
        # This one should have anisou records
        pdbfile3 = read_PDB(output)
        self._compareInputOutputPDBs(pdbfile, pdbfile3)
        for a1, a2 in zip(pdbfile.atoms, pdbfile3.atoms):
            if has_numpy():
                self.assertEqual(a1.anisou.shape, a2.anisou.shape)
            else:
                self.assertEqual(len(a1.anisou), len(a2.anisou))
            for x, y in zip(a1.anisou, a2.anisou):
                self.assertAlmostEqual(x, y, delta=1e-4)
            self.assertEqual(len(a1.other_locations), len(a2.other_locations))
            for key in sorted(a1.other_locations.keys()):
                oa1 = a1.other_locations[key]
                oa2 = a2.other_locations[key]
                if has_numpy():
                    self.assertEqual(oa1.anisou.shape, oa2.anisou.shape)
                else:
                    self.assertEqual(len(oa1.anisou), len(oa2.anisou))
                for x, y in zip(oa1.anisou, oa2.anisou):
                    self.assertAlmostEqual(x, y, delta=1e-4)

    def testPDBWriteFormat(self):
        """ Test PDB atom names are properly justified per PDB standard """
        pdbfile = read_PDB(self.format_test)
        f = get_fn('pdb_format_test.pdb', written=True)
        pdbfile.write_pdb(f, write_anisou=True)
        self.assertTrue(diff_files(get_saved_fn('SCM_A_formatted.pdb'), f))

    @unittest.skipIf(skip_big_tests(), 'Skipping large tests')
    def testSegidHandling(self):
        """ Test handling of CHARMM-specific SEGID identifier (r/w) """
        pdbfile = read_PDB(self.overflow2)
        allsegids = set(['PROA', 'PROB', 'CARA', 'CARE', 'CARC', 'CARD', 'CARB',
                         'MEMB', 'TIP3', 'POT', 'CLA'])
        foundsegids = set()
        for atom in pdbfile.atoms:
            self.assertTrue(hasattr(atom, 'segid'))
            foundsegids.add(atom.segid)
        self.assertEqual(foundsegids, allsegids)
        self.assertEqual(pdbfile.atoms[0].segid, 'PROA')
        self.assertEqual(pdbfile.atoms[5161].segid, 'PROA')
        self.assertEqual(pdbfile.atoms[5162].segid, 'PROB')
        self.assertEqual(pdbfile.atoms[-1].segid, 'CLA')
        f = get_fn('pdb_segid_test1.pdb', written=True)
        f2 = get_fn('pdb_segid_test2.pdb', written=True)
        pdbfile.write_pdb(f)
        pdbfile2 = read_PDB(f)
        for atom in pdbfile2.atoms:
            self.assertFalse(hasattr(atom, 'segid'))
        pdbfile.write_pdb(f2, charmm=True)
        pdbfile3 = read_PDB(f2)
        for atom in pdbfile3.atoms:
            self.assertTrue(hasattr(atom, 'segid'))
            self.assertEqual(atom.segid, pdbfile.atoms[atom.idx].segid)

    def _compareInputOutputPDBs(self, pdbfile, pdbfile2, reordered=False,
                                altloc_option='all'):
        # Now go through all atoms and compare their attributes
        for a1, a2 in zip(pdbfile.atoms, pdbfile2.atoms):
            if altloc_option in ('first', 'all'):
                self.assertEqual(a1.occupancy, a2.occupancy)
                a1idx = a1.idx
            elif altloc_option == 'occupancy':
                a, occ = a1, a1.occupancy
                for key, oa in iteritems(a1.other_locations):
                    if oa.occupancy > occ:
                        occ = oa.occupancy
                        a = oa
                a1idx = a1.idx
                a1 = a # This is the atom we want to compare with
            self.assertEqual(a1.atomic_number, a2.atomic_number)
            self.assertEqual(a1.name, a2.name)
            self.assertEqual(a1.type, a2.type)
            self.assertEqual(a1.mass, a2.mass)
            self.assertEqual(a1.charge, a2.charge)
            self.assertEqual(a1.bfactor, a2.bfactor)
            self.assertEqual(a1.altloc, a2.altloc)
            self.assertEqual(a1idx, a2.idx)
            if altloc_option == 'all':
                self.assertEqual(set(a1.other_locations.keys()),
                                 set(a2.other_locations.keys()))
            self.assertEqual(a1.xx, a2.xx)
            self.assertEqual(a1.xy, a2.xy)
            self.assertEqual(a1.xz, a2.xz)
            if altloc_option != 'all':
                # There should be no alternate locations unless we keep them all
                self.assertEqual(len(a2.other_locations), 0)
            if not reordered:
                self.assertEqual(a1.number, a2.number)
            # Search all alternate locations as well
            for k1, k2 in zip(sorted(a1.other_locations.keys()),
                              sorted(a2.other_locations.keys())):
                self.assertEqual(k1, k2)
                oa1 = a1.other_locations[k1]
                oa2 = a2.other_locations[k2]
                self.assertEqual(oa1.atomic_number, oa2.atomic_number)
                self.assertEqual(oa1.name, oa2.name)
                self.assertEqual(oa1.type, oa2.type)
                self.assertEqual(oa1.mass, oa2.mass)
                self.assertEqual(oa1.charge, oa2.charge)
                self.assertEqual(oa1.occupancy, oa2.occupancy)
                self.assertEqual(oa1.bfactor, oa2.bfactor)
                self.assertEqual(oa1.altloc, oa2.altloc)
                self.assertEqual(oa1.idx, oa2.idx)
                if not reordered:
                    self.assertEqual(oa1.number, oa2.number)
        # Now compare all residues
        for r1, r2 in zip(pdbfile.residues, pdbfile2.residues):
            self.assertEqual(r1.name, r2.name)
            self.assertEqual(r1.idx, r2.idx)
            self.assertEqual(r1.ter, r2.ter)
            self.assertEqual(len(r1), len(r2))
            self.assertEqual(r1.insertion_code, r2.insertion_code)
            if not reordered:
                self.assertEqual(r1.number, r2.number)

    # Private helper test functions
    def _check4lzt(self, obj, check_meta=True, has_altloc=True):
        self.assertEqual(obj.get_coordinates('all').shape[0], 1)
        np.testing.assert_allclose(obj.box,
                         [27.24, 31.87, 34.23, 88.52, 108.53, 111.89])
        self.assertEqual(obj.space_group, 'P 1')
        self.assertEqual(len(obj.atoms), 1164)
        self.assertEqual(len(obj.residues[0]), 9)
        # Check that alternate conformations are taken into account
        total_natoms = 0
        for i, atom in enumerate(obj.atoms):
            total_natoms += 1
            for key in atom.other_locations:
                total_natoms += 1
                atom2 = atom.other_locations[key]
                self.assertEqual(atom.altloc, 'A')
                self.assertEqual(atom2.altloc, 'B')
                if i in [388, 389]:
                    # Sum of atom 388/389 occupancies is 1.02
                    self.assertEqual(atom2.occupancy + atom.occupancy, 1.02)
                else:
                    # Other atoms occupancy sums are 1 exactly
                    self.assertEqual(atom2.occupancy + atom.occupancy, 1)
        if has_altloc:
            self.assertEqual(total_natoms, 1183)
            self.assertEqual(len(obj.atoms), 1164)
        else:
            self.assertEqual(total_natoms, 1164) # 19 atoms have altlocs
        # Check the metadata
        if check_meta:
            self.assertEqual(obj.experimental, 'X-RAY DIFFRACTION')
            self.assertEqual(len(obj.residues), 274)
            self.assertEqual(obj.pmid, '9761848')
            self.assertEqual(obj.journal_authors, 'M.A.WALSH,T.R.SCHNEIDER,'
                             'L.C.SIEKER,Z.DAUTER,V.S.LAMZIN,K.S.WILSON')
            self.assertEqual(obj.journal, 'ACTA CRYSTALLOGR.,SECT.D')
            self.assertEqual(obj.year, 1998)
            self.assertEqual(obj.keywords, ['HYDROLASE', 'O-GLYCOSYL',
                             'GLYCOSIDASE'])
            self.assertEqual(obj.title, 'REFINEMENT OF TRICLINIC HEN EGG-WHITE '
                             'LYSOZYME AT ATOMIC RESOLUTION.')
            self.assertEqual(obj.doi, '10.1107/S0907444997013656')
            self.assertEqual(obj.volume, '54')
            self.assertEqual(obj.page, '522')
            self.assertEqual(obj.resolution, 0.95)
        # Check the TER card is picked up
        for i, residue in enumerate(obj.residues):
            if i == 128:
                self.assertTrue(residue.ter)
            else:
                self.assertFalse(residue.ter)

class TestParmedPQRStructure(FileIOTestCase):
    """ Tests the PQR parser and writer """

    def testPQRParsing(self):
        """ Tests parsing a PQR file """
        pqr = formats.PQRFile.parse(get_fn('adk_open.pqr'))
        self.assertIsInstance(pqr, Structure)
        self.assertEqual(len(pqr.atoms), 3341)
        self.assertEqual(len(pqr.residues), 214)
        self.assertAlmostEqual(sum(a.charge for a in pqr.atoms), -4, places=4)
        self.assertEqual(pqr.atoms[0].charge, -0.30)
        self.assertEqual(pqr.atoms[0].radii, 1.85)
        self.assertEqual(pqr.atoms[0].atomic_number, 7)
        self.assertEqual(pqr.atoms[35].charge, -0.8)
        self.assertEqual(pqr.atoms[-1].charge, -0.67)
        self.assertEqual(pqr.atoms[-1].radii, 1.7)
        self.assertEqual(pqr.atoms[-1].atomic_number, 8)

    def testPQRWriter(self):
        """ Tests writing a PQR file with charges and radii """
        parm = formats.load_file(get_fn('trx.prmtop'), get_fn('trx.inpcrd'))
        # Create multiple models
        coords = []
        coords.append(parm.coordinates)
        coords.append(parm.coordinates + 1)
        coords.append(parm.coordinates + 2)
        parm.coordinates = np.vstack(coords)
        formats.PQRFile.write(parm, get_fn('test.pqr', written=True),
                              renumber=True)
        pqr = formats.PQRFile.parse(get_fn('test.pqr', written=True))
        self.assertEqual(len(parm.atoms), len(pqr.atoms))
        for a1, a2 in zip(parm.atoms, pqr.atoms):
            self.assertEqual(a1.name, a2.name)
            self.assertEqual(a1.residue.name, a2.residue.name)
            self.assertEqual(a1.residue.idx, a2.residue.idx)
            self.assertAlmostEqual(a1.charge, a2.charge)
            self.assertAlmostEqual(a1.radii, a2.radii)
        self.assertEqual(pqr.get_coordinates().shape[0], 3)
        np.testing.assert_allclose(pqr.get_coordinates(0),
                                   parm.get_coordinates(0), atol=2e-3)

    def testPQRWithElement(self):
        """ Tests reading a PQR file that has an element column """
        self.assertTrue(formats.PQRFile.id_format(get_fn('elem.pqr')))
        pqr = formats.PQRFile.parse(get_fn('elem.pqr'))
        self.assertEqual(len(pqr.atoms), 458)
        self.assertEqual(len(pqr.residues), 14)
        self.assertEqual(pqr.atoms[0].charge, -0.9526)
        self.assertEqual(pqr.atoms[-1].radii, 0.8)

class TestChemistryCIFStructure(FileIOTestCase):

    def setUp(self):
        self.lztpdb = get_fn('4lzt.pdb')
        self.lzt = get_fn('4LZT.cif')
        self.largecif = get_fn('1ffk.cif')
        FileIOTestCase.setUp(self)

    def testWriteCIF(self):
        """ Test CIF writing capabilities """
        cif = read_CIF(self.lzt)
        written = get_fn('test.cif', written=True)
        cif.write_cif(written, renumber=False, write_anisou=True)
        cif2 = read_CIF(written)
        # cif and cif2 should have equivalent atom properties (basically,
        # everything should be the same except the metadata)
        self.assertEqual(len(cif.atoms), len(cif2.atoms))
        self.assertEqual(len(cif.residues), len(cif2.residues))

        # Check residue properties
        for res1, res2 in zip(cif.residues, cif2.residues):
            self.assertEqual(len(res1), len(res2))
            self.assertEqual(res1.name, res2.name)
            self.assertEqual(res1.chain, res2.chain)
            self.assertEqual(res1.insertion_code, res2.insertion_code)
            self.assertEqual(res1.number, res2.number)

        # Check atom properties
        for a1, a2 in zip(cif.atoms, cif2.atoms):
            self.assertEqual(a1.name, a2.name)
            self.assertEqual(a1.number, a2.number)
            self.assertEqual(a1.element, a2.element)
            self.assertEqual(a1.altloc, a2.altloc)
            self.assertEqual(a1.xx, a2.xx)
            self.assertEqual(a1.xy, a2.xy)
            self.assertEqual(a1.xz, a2.xz)
            self.assertEqual(len(a1.anisou), 6)
            self.assertEqual(len(a2.anisou), 6)
            for x, y in zip(a1.anisou, a2.anisou):
                self.assertEqual(x, y)

        # Check box
        self.assertEqual(len(cif.box), len(cif2.box))
        for x, y in zip(cif.box, cif2.box):
            self.assertEqual(x, y)

        # Now check CIF writing without anisotropic B-factors and with
        # renumbering
        io = StringIO()
        cif.write_cif(io)
        io.seek(0)
        cif3 = read_CIF(io)
        # cif and cif3 should have equivalent atom properties (basically,
        # everything should be the same except the metadata)
        self.assertEqual(len(cif.atoms), len(cif3.atoms))
        self.assertEqual(len(cif.residues), len(cif3.residues))

        # Check residue properties
        i = 1
        for res1, res2 in zip(cif.residues, cif3.residues):
            self.assertEqual(len(res1), len(res2))
            self.assertEqual(res1.name, res2.name)
            self.assertEqual(res1.chain, res2.chain)
            self.assertEqual(res1.insertion_code, res2.insertion_code)
            self.assertEqual(res2.number, i)
            i += 1

        # Check atom properties
        i = 1
        for a1, a2 in zip(cif.atoms, cif3.atoms):
            self.assertEqual(a1.name, a2.name)
            self.assertEqual(a2.number, i)
            self.assertEqual(a1.element, a2.element)
            self.assertEqual(a1.altloc, a2.altloc)
            self.assertEqual(a1.xx, a2.xx)
            self.assertEqual(a1.xy, a2.xy)
            self.assertEqual(a1.xz, a2.xz)
            self.assertIs(a2.anisou, None)
            i += 1 + len(a2.other_locations)

        # Check box
        self.assertEqual(len(cif.box), len(cif3.box))
        for x, y in zip(cif.box, cif3.box):
            self.assertEqual(x, y)

    def test4LZT(self):
        """ Test CIF parsing on 4LZT (w/ ANISOU, altlocs, etc.) """
        self._check4lzt(read_CIF(self.lzt))

    def testDownload(self):
        """ Test CIF downloading on 4LZT """
        self._check4lzt(download_CIF('4lzt'))

    def testCIFModels(self):
        """ Test CIF parsing/writing NMR structure with 20 models (2koc) """
        cif = download_CIF('2koc')
        self.assertEqual(cif.get_coordinates('all').shape, (20, 451, 3))
        self.assertEqual(len(cif.atoms), 451)
        output = StringIO()
        write_CIF(cif, output)
        output.seek(0)
        pdbfile2 = read_CIF(output)
        self.assertEqual(len(pdbfile2.atoms), 451)
        self.assertEqual(pdbfile2.get_coordinates('all').shape, (20, 451, 3))
        np.testing.assert_allclose(pdbfile2.get_coordinates('all'),
                                   cif.get_coordinates('all'))

    def testCIFWriteStandardNames(self):
        """ Test PDBx/mmCIF file writing converting to standard names """
        parm = formats.load_file(get_fn('trx.prmtop'), get_fn('trx.inpcrd'))
        output = StringIO()
        write_CIF(parm, output, standard_resnames=True)
        output.seek(0)
        pdb = read_CIF(output)
        for res in pdb.residues:
            self.assertEqual(
                    residue.AminoAcidResidue.get(res.name).abbr, res.name
            )

    def _check4lzt(self, cif):
        pdb = read_PDB(self.lztpdb)
        self.assertEqual(len(cif.atoms), len(pdb.atoms))
        nextra = 0
        for a1, a2 in zip(cif.atoms, pdb.atoms):
            self.assertEqual(a1.name, a2.name)
            self.assertEqual(a1.number + nextra, a2.number)
            self.assertEqual(len(a1.anisou), len(a2.anisou))
            for x, y in zip(a1.anisou, a2.anisou):
                self.assertEqual(x, y)
            self.assertEqual(a1.altloc, a2.altloc)
            self.assertEqual(len(a1.other_locations), len(a2.other_locations))
            self.assertEqual(a1.residue.name, a2.residue.name)
            self.assertEqual(a1.residue.number, a2.residue.number)
            # TER cards consume a serial number in the PDB file, but *not* in a
            # CIF file.
            if a2.residue.ter and a2 is a2.residue.atoms[-1]:
                nextra += 1
        # Check the unit cell info
        self.assertEqual(cif.box[0], 27.240)
        self.assertEqual(cif.box[1], 31.870)
        self.assertEqual(cif.box[2], 34.230)
        self.assertEqual(cif.box[3], 88.520)
        self.assertEqual(cif.box[4], 108.53)
        self.assertEqual(cif.box[5], 111.89)
        # Check the metadata now
        self.assertEqual(cif.experimental, 'X-RAY DIFFRACTION')
        self.assertEqual(cif.authors,
                'Walsh, M.A., Schneider, T., Sieker, L.C., Dauter, Z., '
                'Lamzin, V., Wilson, K.S.')
        self.assertEqual(cif.title,
                'Refinement of triclinic hen egg-white lysozyme at atomic '
                'resolution.; Refinement of Triclinic Lysozyme: I. Fourier '
                'and Least-Squares Methods; Refinement of Triclinic Lysozyme: '
                'II. The Method of Stereochemically Restrained Least Squares')
        self.assertEqual(cif.journal,
                'Acta Crystallogr.,Sect.D; Acta Crystallogr.,Sect.B; '
                'Acta Crystallogr.,Sect.B')
        self.assertEqual(cif.journal_authors,
                'Walsh, M.A., Schneider, T.R., Sieker, L.C., Dauter, Z., '
                'Lamzin, V.S., Wilson, K.S., Hodsdon, J.M., Brown, G.M., '
                'Jensen, L.H., Ramanadham, M.')
        self.assertEqual(cif.year, '1998, 1990, 1990')
        self.assertEqual(cif.page, '522, 54, 63')
        self.assertEqual(cif.keywords, ['HYDROLASE', 'O-GLYCOSYL',
                                        'GLYCOSIDASE'])
        self.assertEqual(cif.volume, '54, 46, 46')
        self.assertEqual(cif.doi, '10.1107/S0907444997013656')
        self.assertEqual(cif.pmid, '9761848')
        self.assertEqual(cif.resolution, 0.95)

class TestMol2File(FileIOTestCase):
    """ Tests the correct parsing and processing of mol2 files """

    def testMultiMol2(self):
        """ Tests the parsing of a mol2 file with multiple residues """
        cont = formats.Mol2File.parse(get_fn('test_multi.mol2'))
        self.assertIsInstance(cont, ResidueTemplateContainer)
        self.assertEqual(len(cont), 20)
        for i, res in enumerate(cont):
            if i == 0:
                self.assertEqual(res.name, 'DA5')
                self.assertIs(res.head, None)
                self.assertIs(res.tail, [a for a in res if a.name == "O3'"][0])
                self.assertEqual(len(res), 30)
            elif i < 9:
                self.assertEqual(res.name, 'DA')
                self.assertIs(res.head, [a for a in res if a.name == "P"][0])
                self.assertIs(res.tail, [a for a in res if a.name == "O3'"][0])
                self.assertEqual(len(res), 32)
            elif i == 9:
                self.assertEqual(res.name, 'DA3')
                self.assertIs(res.head, [a for a in res if a.name == "P"][0])
                self.assertIs(res.tail, None)
                self.assertEqual(len(res), 33)
            elif i == 10:
                self.assertEqual(res.name, 'DT5')
                self.assertIs(res.head, None)
                self.assertIs(res.tail, [a for a in res if a.name == "O3'"][0])
                self.assertEqual(len(res), 30)
            elif i < 19:
                self.assertEqual(res.name, 'DT')
                self.assertIs(res.head, [a for a in res if a.name == "P"][0])
                self.assertIs(res.tail, [a for a in res if a.name == "O3'"][0])
                self.assertEqual(len(res), 32)
            elif i == 19:
                self.assertEqual(res.name, 'DT3')
                self.assertIs(res.head, [a for a in res if a.name == "P"][0])
                self.assertIs(res.tail, None)
                self.assertEqual(len(res), 33)
        # There are 686 total bonds defined in the mol2 file. However, there are
        # 20 residues, of which only 2 of the termini are *not* bonded to the
        # next residue. Ergo, 18 of those 686 bonds are intra-residue, and so
        # are not added to any of the ResidueTemplate instances. As a result, we
        # should have 686 - 18 = 668 total bonds if we add up the lengths of the
        # bond arrays for every residue
        self.assertEqual(sum([len(x.bonds) for x in cont]), 668)

    def testMultiMol2Entries(self):
        """ Tests a mol2 file with multiple @<MOLECULE> sections """
        cont = formats.Mol2File.parse(get_fn('multimol.mol2'))
        self.assertIsInstance(cont, ResidueTemplateContainer)
        self.assertEqual(len(cont), 200)
        for i, res in enumerate(cont):
            self.assertEqual(res.name, 'ZINC00000016_%d' % (i+1))
            self.assertEqual(len(res.atoms), 37)
            self.assertEqual(len(res.bonds), 38)
            self.assertIs(res.head, None)
            self.assertIs(res.tail, None)

    def testMultiMol2Structure(self):
        """ Tests parsing a multi-residue mol2 into a Structure """
        struct = formats.Mol2File.parse(get_fn('test_multi.mol2'),
                                        structure=True)
        self.assertIsInstance(struct, Structure)
        self.assertEqual(len(struct.residues), 20)
        for i, res in enumerate(struct.residues):
            if i == 0:
                self.assertEqual(res.name, 'DA5')
                self.assertEqual(len(res), 30)
            elif i < 9:
                self.assertEqual(res.name, 'DA')
                self.assertEqual(len(res), 32)
            elif i == 9:
                self.assertEqual(res.name, 'DA3')
                self.assertEqual(len(res), 33)
            elif i == 10:
                self.assertEqual(res.name, 'DT5')
                self.assertEqual(len(res), 30)
            elif i < 19:
                self.assertEqual(res.name, 'DT')
                self.assertEqual(len(res), 32)
            elif i == 19:
                self.assertEqual(res.name, 'DT3')
                self.assertEqual(len(res), 33)
        # This should have the total number of bonds, 686
        self.assertEqual(len(struct.bonds), 686)

    def testMol3File(self):
        """ Tests parsing a Mol3 file into a ResidueTemplate """
        mol3 = formats.Mol2File.parse(get_fn('tripos9.mol2'))
        self.assertIsInstance(mol3, ResidueTemplate)
        self.assertEqual(mol3.name, 'GPN')
        self.assertEqual(len(mol3), 34)
        self.assertEqual(len(mol3.bonds), 35)
        self.assertIs(mol3.head, [a for a in mol3 if a.name == "N1'"][0])
        self.assertIs(mol3.tail, [a for a in mol3 if a.name == "C'"][0])

    def testMol3File2(self):
        """ Tests parsing a Mol3 file with RESIDUECONNECT atoms """
        mol3 = formats.Mol2File.parse(get_fn('m2-c1_f3.mol2'))
        self.assertEqual(len(mol3.atoms), 27)
        self.assertEqual(len(mol3.bonds), 29)
        self.assertIs(mol3.head, None)
        self.assertIs(mol3.tail, None)
        self.assertIs(mol3.connections[0], mol3[5])
        self.assertIs(mol3.connections[1], mol3[9])

    def testMol2FileWithBlankLines(self):
        """ Tests parsing a Mol2 file with blank lines at the end """
        mol2 = formats.Mol2File.parse(get_fn('tripos1.mol2'))
        self.assertIsInstance(mol2, ResidueTemplate)
        self.assertEqual(mol2.name, 'DAN')
        self.assertEqual(len(mol2), 31)
        self.assertEqual(len(mol2.bonds), 33)

    def testMol2FileWithNoTypeNames(self):
        """ Tests writing a Mol2 without types uses names instead """
        struct = read_PDB(get_fn('2koc.pdb'))
        output = StringIO()
        formats.Mol2File.write(struct, output)
        output.seek(0)
        mol2 = formats.Mol2File.parse(output, structure=True)

    def testMol3Structure(self):
        """ Tests parsing a Mol3 file with 1 residue into a Structure """
        mol3 = formats.Mol2File.parse(get_fn('tripos9.mol2'), structure=True)
        self.assertIsInstance(mol3, Structure)
        self.assertEqual(mol3.residues[0].name, 'GPN')
        self.assertEqual(len(mol3.atoms), 34)
        self.assertEqual(len(mol3.bonds), 35)

    def testMol2MultiWrite(self):
        """
        Tests writing mol2 file of multi residues from ResidueTemplateContainer
        """
        mol2 = formats.Mol2File.parse(get_fn('test_multi.mol2'))
        formats.Mol2File.write(mol2, get_fn('test_multi.mol2', written=True))
        formats.Mol2File.write(mol2, get_fn('test_multi_sep.mol2', written=True),
                               split=True)
        self.assertTrue(diff_files(get_saved_fn('test_multi.mol2'),
                                   get_fn('test_multi.mol2', written=True)))
        self.assertTrue(diff_files(get_saved_fn('test_multi_sep.mol2'),
                                   get_fn('test_multi_sep.mol2', written=True)))
        mol22 = formats.Mol2File.parse(get_fn('test_multi_sep.mol2', written=True))
        self.assertEqual(len(mol2), len(mol22))
        self.assertEqual([r.name for r in mol2], [r.name for r in mol22])
        for r1, r2 in zip(mol2, mol22):
            self.assertEqual(len(r1.bonds), len(r2.bonds))
            self.assertEqual(len(r1.atoms), len(r2.atoms))
            self.assertFalse(r1.head is None and r1.tail is None)
            self.assertTrue(r2.head is None and r2.tail is None)
        f = StringIO()
        formats.Mol2File.write(mol2, f, mol3=True, split=True)
        f.seek(0)
        mol3 = formats.Mol2File.parse(f)
        self.assertEqual(len(mol2), len(mol3))
        self.assertEqual([r.name for r in mol2], [r.name for r in mol3])
        for r1, r2 in zip(mol2, mol3):
            self.assertEqual(len(r1.bonds), len(r2.bonds))
            self.assertEqual(len(r1.atoms), len(r2.atoms))
            self.assertFalse(r1.head is None and r1.tail is None)
            self.assertFalse(r2.head is None and r2.tail is None)
            if r1.head is None:
                self.assertIs(r2.head, None)
            else:
                self.assertEqual(r1.head.name, r2.head.name)
            if r1.tail is None:
                self.assertIs(r2.tail, None)
            else:
                self.assertEqual(r1.tail.name, r2.tail.name)

    def testMol2MultiWriteFromStructure(self):
        """ Tests writing mol2 file of multi residues from Structure """
        mol2 = formats.Mol2File.parse(get_fn('test_multi.mol2'), structure=True)
        formats.Mol2File.write(mol2, get_fn('test_multistruct.mol2', written=True))
        self.assertTrue(diff_files(get_fn('test_multistruct.mol2', written=True),
                                   get_saved_fn('test_multistruct.mol2')))

    def testMol3MultiWrite(self):
        """
        Tests writing mol3 file of multi residues from ResidueTemplateContainer
        """
        mol2 = formats.Mol2File.parse(get_fn('test_multi.mol2'))
        formats.Mol2File.write(mol2, get_fn('test_multi.mol3', written=True),
                               mol3=True)
        self.assertTrue(diff_files(get_fn('test_multi.mol3', written=True),
                                   get_saved_fn('test_multi.mol3')))

    def testMol3MultiWriteFromStructure(self):
        """ Tests writing mol3 file of multi residues from Structure """
        mol2 = formats.Mol2File.parse(get_fn('test_multi.mol2'), structure=True)
        formats.Mol2File.write(mol2, get_fn('test_multistruct.mol3', written=True),
                               mol3=True)
        self.assertTrue(diff_files(get_fn('test_multistruct.mol3', written=True),
                                   get_saved_fn('test_multistruct.mol3')))

    def testMol2SingleWrite(self):
        """ Tests writing mol2 file of single ResidueTemplate """
        mol2 = formats.Mol2File.parse(get_fn('tripos9.mol2'))
        formats.Mol2File.write(mol2, get_fn('tripos9.mol2', written=True))
        self.assertTrue(diff_files(get_fn('tripos9.mol2', written=True),
                                   get_saved_fn('tripos9.mol2')))

    def testMol2SingleWriteStruct(self):
        """ Tests writing mol2 file of single-residue Structure """
        mol2 = formats.Mol2File.parse(get_fn('tripos9.mol2'), structure=True)
        formats.Mol2File.write(mol2, get_fn('tripos9struct.mol2', written=True))
        self.assertTrue(diff_files(get_fn('tripos9struct.mol2', written=True),
                                   get_saved_fn('tripos9struct.mol2')))

    def testMol3SingleWrite(self):
        """ Tests writing mol3 file of single ResidueTemplate """
        mol2 = formats.Mol2File.parse(get_fn('tripos9.mol2'))
        formats.Mol2File.write(mol2, get_fn('tripos9.mol3', written=True),
                               mol3=True)
        self.assertTrue(diff_files(get_fn('tripos9.mol3', written=True),
                                   get_saved_fn('tripos9.mol3')))

    def testMol3SingleWriteStruct(self):
        """ Tests writing mol3 file of single-residue Structure """
        mol2 = formats.Mol2File.parse(get_fn('tripos9.mol2'), structure=True)
        formats.Mol2File.write(mol2, get_fn('tripos9struct.mol3', written=True),
                               mol3=True)
        self.assertTrue(diff_files(get_fn('tripos9struct.mol3', written=True),
                                   get_saved_fn('tripos9struct.mol3')))

class TestFileDownloader(unittest.TestCase):
    """ Tests load_file with URLs for each format """

    def setUp(self):
        self.url = 'https://github.com/ParmEd/ParmEd/raw/master/test/files/'

    def testDownloadOFF(self):
        """ Tests automatic loading of downloaded OFF files """
        self.assertTrue(amber.AmberOFFLibrary.id_format(self.url + 'amino12.lib'))
        off = amber.AmberOFFLibrary.parse(self.url + 'amino12.lib')
        self.assertIsInstance(off, dict)
        for key, item in iteritems(off):
            self.assertIsInstance(item, ResidueTemplate)

    def testDownloadAmberParm(self):
        """ Tests automatic loading of downloaded AmberParm object """
        self.assertTrue(amber.AmberFormat.id_format(self.url + 'tip4p.parm7'))
        parm = amber.AmberFormat.parse(self.url + 'tip4p.parm7')
        self.assertIsInstance(parm, amber.AmberParm)

    def testDownloadAmoebaParm(self):
        """ Tests automatic loading of downloaded AmoebaParm object """
        self.assertTrue(amber.AmberFormat.id_format(self.url + 'nma.parm7'))
        parm = amber.AmberFormat.parse(self.url + 'nma.parm7')
        self.assertIsInstance(parm, amber.AmoebaParm)

    def testDownloadChamberParm(self):
        """ Tests automatic loading of downloaded ChamberParm object """
        self.assertTrue(amber.AmberFormat.id_format(self.url + 'ala_ala_ala.parm7'))
        parm = amber.AmberFormat.parse(self.url + 'ala_ala_ala.parm7')
        self.assertIsInstance(parm, amber.ChamberParm)

    def testDownloadAmberFormat(self):
        """ Tests automatic loading of downloaded AmberFormat object """
        self.assertTrue(amber.AmberFormat.id_format(self.url + 'cSPCE.mdl'))
        parm = amber.AmberFormat.parse(self.url + 'cSPCE.mdl')
        self.assertIsInstance(parm, amber.AmberFormat)
        self.assertNotIsInstance(parm, amber.AmberParm)

    def testDownloadAmberRestart(self):
        """ Tests automatic loading of downloaded Amber ASCII restart file """
        self.assertTrue(amber.AmberAsciiRestart.id_format(self.url + 'trx.inpcrd'))
        parm = amber.AmberAsciiRestart(self.url + 'trx.inpcrd')
        self.assertIsInstance(parm, amber.AmberAsciiRestart)

    def testDownloadAmberMdcrd(self):
        """ Tests automatic loading of downloaded Amber mdcrd file """
        self.assertTrue(amber.AmberMdcrd.id_format(self.url + 'tz2.truncoct.crd'))
        crd = amber.AmberMdcrd(self.url + 'tz2.truncoct.crd', natom=5827, hasbox=True)
        self.assertIsInstance(crd, amber.AmberMdcrd)

    def testDownloadCharmmPsfFile(self):
        """ Tests automatic loading of downloaded CHARMM PSF file """
        self.assertTrue(formats.PSFFile.id_format(self.url + 'ala_ala_ala.psf'))
        parm = formats.PSFFile.parse(self.url + 'ala_ala_ala.psf')
        self.assertIsInstance(parm, charmm.CharmmPsfFile)

    def testDownloadCharmmCrdFile(self):
        """ Tests automatic loading of downloaded CHARMM crd file """
        self.assertTrue(charmm.CharmmCrdFile.id_format(self.url + 'dhfr_min_charmm.crd'))
        crd = charmm.CharmmCrdFile(self.url + 'dhfr_min_charmm.crd')
        self.assertIsInstance(crd, charmm.CharmmCrdFile)

    def testDownloadCharmmRestart(self):
        """ Tests automatic loading of downloaded CHARMM restart file """
        self.assertTrue(charmm.CharmmRstFile.id_format(self.url + 'sample-charmm.rst'))
        crd = charmm.CharmmRstFile(self.url + 'sample-charmm.rst')
        self.assertIsInstance(crd, charmm.CharmmRstFile)

    def testDownloadPDB(self):
        """ Tests automatic loading of downloaded PDB files """
        self.assertTrue(formats.PDBFile.id_format(self.url + '4lzt.pdb'))
        pdb = formats.PDBFile.parse(self.url + '4lzt.pdb')
        self.assertIsInstance(pdb, Structure)
        self.assertEqual(len(pdb.atoms), 1164)

    def testDownloadCIF(self):
        """ Tests automatic loading of downloaded PDBx/mmCIF files """
        self.assertTrue(formats.CIFFile.id_format(self.url + '4LZT.cif'))
        cif = formats.CIFFile.parse(self.url + '4LZT.cif')
        self.assertIsInstance(cif, Structure)
        self.assertEqual(len(cif.atoms), 1164)

    def testDownloadMol2(self):
        """ Tests automatic loading of downloaded mol2 and mol3 files """
        self.assertTrue(formats.Mol2File.id_format(self.url + 'test_multi.mol2'))
        self.assertTrue(formats.Mol2File.id_format(self.url + 'tripos9.mol2'))
        mol2 = formats.Mol2File.parse(self.url + 'test_multi.mol2')
        self.assertIsInstance(mol2, ResidueTemplateContainer)
        mol3 = formats.Mol2File.parse(self.url + 'tripos9.mol2')
        self.assertIsInstance(mol3, ResidueTemplate)

    def testDownloadGromacsTop(self):
        """ Tests automatic loading of downloaded Gromacs topology file """
        self.assertTrue(gromacs.GromacsTopologyFile.id_format(self.url + '1aki.charmm27.top'))
        top = gromacs.GromacsTopologyFile(self.url + '1aki.charmm27.top')
        self.assertIsInstance(top, gromacs.GromacsTopologyFile)

    def testDownloadGromacsGro(self):
        """ Tests automatic loading of downloaded Gromacs GRO file """
        self.assertTrue(gromacs.GromacsGroFile.id_format(self.url + '1aki.ff99sbildn.gro'))
        gro = gromacs.GromacsGroFile.parse(self.url + '1aki.ff99sbildn.gro')
        self.assertIsInstance(gro, Structure)

del skip_big_tests # Avoid fake testing this method :)
